[build]
builder = "nixpacks"

[deploy]
startCommand = "bundle exec rails server -p $PORT -e production"
healthcheckPath = "/up"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
